services:
  web:
    container_name: web
    depends_on:
      - db
      - redis
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=gddgdd
      - DB_NAME=hillel_django
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_PORT=5432
    command: ["gunicorn", "-c", "gunicorn_config.py", "hillel_django.wsgi"]
    restart: always
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_PORT=5432
      - DB_NAME=postgres
      - DEBUG=True
    command: ["python", "manage.py", "migrate"]
    restart: on-failure
  db:
    image: "postgres:15"
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
  redis:
    image: "redis:latest"
    ports:
      - "63799:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=postgres
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_PORT=5432
    command: ["celery", "-A", "hillel_django.celery", "worker", "-l", "info", "--beat"]
    restart: on-failure
