# Generated by Django 4.2.7 on 2023-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefApp', '0002_store_storeinventory_store_products_product_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='exclusive_features',
            field=models.TextField(blank=True),
        ),
    ]
