# Generated by Django 4.2.7 on 2023-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefApp', '0003_remove_storeinventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
