# Generated by Django 4.1.6 on 2023-11-03 18:56

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                validators=[products.models.product.non_negative_validator]
            ),
        ),
    ]
