# Generated by Django 4.2.7 on 2023-11-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_store_alter_product_category_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(through='products.StoreInventory', to='products.store'),
        ),
    ]
