# Generated by Django 4.2.7 on 2023-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_alter_product_category_orderproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField()),
                ('opening_hours', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
