# Generated by Django 4.2.7 on 2023-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_market_storeinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='count_of_product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
