# Generated by Django 4.2.7 on 2023-11-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_storeinventory_count_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='market',
        ),
    ]
