# Generated by Django 4.2.7 on 2023-11-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_storeinventory_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='market',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='products.market'),
            preserve_default=False,
        ),
    ]
