# Generated by Django 4.2.7 on 2023-11-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_stores_store_products_storeinventory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
