# Generated by Django 4.2.7 on 2023-11-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storeinventory_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='market',
        ),
    ]
