# Generated by Django 4.2.7 on 2023-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_storeinventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(),
        ),
    ]
